dict = {
	server_host: `Хост Сервера`,
	server_host_submit: `Изменить`,
	logout: `Выход`,
	high_damage_numbers_patch: `Патч Высоких Значений Урона`,
	skip_mission_start_timer: `Пропустить Таймер Запуска Миссии`,
	simulacrum_blacklisted: `Враги из черного списка в Симулякруме`,
	simulacrum_whitelisted: `Враги из белого списка в Симулякруме`,
	pause_always_stops_time: `Пауза Всегда Останавливает Время`,
	ee_log_in_console: `EE.log в Консоль`,
	fov_override: `Перезапись FOV (0 = отключена)`,
	save_config: `Сохранить изменения в client_config.json`,

	camtype: `Тип Камеры`,
	gamecam: `Нормальная`,
	freecam: `Свободная`,
	lockcam: `Фиксированная`,
	pos: `Позиция`,
	tp_submit: `Телепортироваться к`,
	custom: `Пользовательское`,
	marker: `|TYPE| через |DIST|м`,
	marker_unk: `Метка`,
	marker_obj: `Цель`,
	marker_target: `Цель`,
	marker_surcap: `Капсула Жизнеобеспечения`,
	marker_surpup: `Модуль Жизнеобеспечения`,
	marker_a: `A`,
	marker_b: `B`,
	marker_c: `C`,
	marker_wp: `Метка`,
	marker_focus: `Фокус`,
	marker_extract: `Эвакуация`,

	enable_auto_start: `Включить Авто Запуск`,
	disable_auto_start: `Отключить Авто Запуск`,
	clear_script_log: `Очистить Лог Скриптов`,
	console: `Консоль`,

	err: `Соединение с DLL потеряно.`,
	err_retry: `Попытка восстановить соединение.`,
}